### PR TITLE
1.0.5 cran revisions

### PR DESCRIPTION
**Pull request by JSchoenbachler**
Addresses issue https://github.com/hugheylab/seeker/issues/37 except for the description text.

@jakejh I made the seeker function return the dry run result instead of printing using `cat()`, but for the system dependency functions I revised them to use the `message()` function and keep the message logging. Let me know if you want to take a different approach!

### CODE REVIEW

**Comment by jakejh** [comment]
1. Code does not need to pass `rprofileDir` to `addToProfile()` if `type=='OS'`.
2. Is the `'\n'` necessary for `message()`?
3. Get rid of the text in the documentation about cran policies.
4. Simplify logic and documentation or `refgenieDir`. No checking for endsWith and no deciding about whether to append.
5. For the dry run, can we not print the message and still return invisible?

**Comment by JSchoenbachler** [comment]
Changes reflect everything except your last point. Here is the relevant text of what she said about this (emphasis mine):

"You write information messages to the console that cannot be easily
suppressed.
**It is more R like to generate objects that can be used to extract the
information a user is interested in, and then print() that object.**
Instead of print()/cat() rather use message()/warning() or
if(verbose)cat(..) (or maybe stop()) if you really have to write text to
the console.
(except for print, summary, interactive functions)"

Further on she says that message can be used instead, so would you rather me just replace with message?

**Comment by jakejh** [comment]
Yes, when I said "print message", I meant to use `message()`.

**Comment by JSchoenbachler** [comment]
Done!

**Comment by jakejh** [comment]
Why was your code for `refgenieDir` error-prone?

**Comment by JSchoenbachler** [comment]
If refgenieDir was NULL (which is possible at that step) then it would error.

**Review by jakejh — APPROVED** [review]
Not sure why the GH actions are failing to install R, but this PR looks good to go! Merge when ready.

**Pull request merged**
