### PR TITLE
Install system deps function

### PR DESCRIPTION
**Pull request by JSchoenbachler**
- Adds function to install system dependencies.
- Adds dryRun argument to seeker function.

NOTE: I'm not currently exporting the system dependency install function. Once this is approved (and any last changes are made to the function), I'll document and export it before merging!

### CODE REVIEW

**Comment by JSchoenbachler** [comment]
Not sure why, but for some reason Mac check is failing when trying to install system dependencies. Retrying it a few times then just waiting until later if it still fails.

**Comment by jakejh** [comment]
Have you run lintr?

**Comment by jakejh** [comment]
General comments:
1. Two empty lines between functions.
2. All functions have an explicit return statement.
3. No closing braces on their own lines.

**Comment by jakejh** [comment]
And please put all functions related to installing system dependencies in a separate file, so they're not in utils.R.

**Comment by jakejh** [comment]
Is `trimSlashes()` really necessary? I know `file.path()` will result in two slashes, but in my experience, this doesn't have any functional consequences. Maybe it's different for system commands.

**Comment by JSchoenbachler** [comment]
I don't know if it's strictly necessary but I just had it just in case. It's mostly in case someone enters a directory as `~/` rather than `~` or something similar. I was just trying to be proactive and make sure we didn't have any issues on that front in case it popped up.

I can do some testing to see if you'd like?

**Comment by jakejh** [comment]
In general, before adding code and complexity, it's a good idea to test whether it's actually necessary.

**Comment by JSchoenbachler** [comment]
You were right, it wasn't necessary. Removed and pushed with update.

**Comment by jakejh** [comment]
Is it not necessary to create the user settings file for the sra toolkit?

**Comment by JSchoenbachler** [comment]
I have been thinking about that, and my current answer is I don't think so (with a question mark). If you look at the action, we don't have to create it for either Mac or Linux in the actions run. I can run some more tests locally and on the Ubuntu EC2 instance to see what behavior happens when installing different ways.

**Comment by JSchoenbachler** [comment]
Here is the relevant section from actions: https://github.com/hugheylab/actions/blob/510a2132ec6eba2e728f4fd65948105e96ef0392/R-CMD-check/action.yaml#L21-L47

**Comment by jakejh** [comment]
Hmm, have you tested this on your local machine and on EC2?
Why is the RCurl package required now? I guess there's no base function that can do the same thing as `getURL()`?

**Comment by jakejh** [comment]
It may not be required on GH actions, but in my testing on EC2 just now, it's definitely required in order to run sra toolkit commands from the terminal (outside of R, but after installing using seeker).

**Comment by JSchoenbachler** [comment]
I have a different fix for it. The manual creation wasn't working for me for some reason, but this new way just runs `vdb-config --interactive` but kills it after a couple of seconds, which sets up a basic configuration.

**Comment by JSchoenbachler** [comment]
RE: RCurl - I was just implementing this the same way `pmparser` was querying the FTP site and parsing out the files. I didn't do any shopping around in the base functions to see if there is an alternative, just copy/pasted from `pmparser`.

**Comment by jakejh** [comment]
That method of using vdb-config doesn't work for me, it just throws me into another screen from which I cannot escape.

**Comment by JSchoenbachler** [comment]
Yeah it worked for me but I'm not sure what the deal is. I was mostly testing to see what would happen on GH Actions. I'm reverting now and doing some more testing.

**Comment by JSchoenbachler** [comment]
I think I got this fixed. Instead of setting "LIBS/IMAGE_GUID" It had to be "LIBS/GUID". Re-running the check to confirm and then it should be good!

**Pull request closed without merging**
