### PR TITLE
Skip steps if commands are missing

### PR DESCRIPTION
**Pull request by JSchoenbachler**
This skips tests if the commands aren't found. Used a modified version of your `assertCommand` function.

### CODE REVIEW

**Comment by jakejh** [comment]
I find the notation really confusing, e.g., `!missingCommands[command == 'ascp',]$exists`. Please simplify considerably. There's also a misspelling.

**Comment by jakejh** [comment]
It's good, I think we can make it better.

1. The new function still seems more complicated than necessary.
2. It seems weird to have a "command" be "salmon_index".
2. Never use `:::` in production code or tests.
3. Use `[...]` instead of`[...,]` with data.tables.
4. One line in particular needs a line break.

**Comment by JSchoenbachler** [comment]
@jakejh I think I addressed these:
1. Simplified by getting rid of the if statement and just creating a new data.table object.
2. Changed column name to `filename`
3. Removed.
4. Changed.
5. Added a line break to the setting of `commandsDt`.

**Comment by jakejh** [comment]
1. Better.
2. Ok, not worth trying to come up with a better name at this point.
3. Good.
4. Are you sure?
5. Personally, I would add a line break after `rbind`, to avoid excessive indentation. Same with line 38.

**Comment by JSchoenbachler** [comment]
@jakejh I think its good now!

**Review by jakejh — APPROVED** [review]

**Pull request merged**
